import type { Metadata } from "next";
import Navbar from "@/components/NavbarWrapper"
import "./globals.css"
import { Inter } from "next/font/google"
import type React from "react" // Added import for React
import { ThemeProvider } from "@/components/theme-provider"

const inter = Inter({ subsets: ["latin"] })



export const metadata: Metadata = {
  title: "Natbrunt-blog",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider 
          attribute="class" 
          defaultTheme="system" 
          enableSystem
          disableTransitionOnChange
          >
          <Navbar />
          <main className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-6">{children}</main>
        </ThemeProvider>
      </body>
    </html>
  )
}

